tft_vocab = {
    'syri': 'syndra',
    'syra': 'syndra',
    'cnra': 'syndra',
    'sher': 'shitter',
    'morana': 'morgana',
    'kean': 'kayn',
    'kane': 'kayn',
    'zyus': 'zyra',
    'zar': 'zyra',
    'sako': 'soraka',
    'rocka': 'soraka',
    'server': 'sivir',
    'kabuko': 'kobuko',
    'kuko': 'kobuko',
    'kabo': 'kobuko',
    'atrox': 'aatrox',
    'atro': 'aatrox',
    'bs': 'bf',
    'story champion': 'storied champion',
    'garin': 'garen',
    'garrett': 'garen',
    'gar': 'garen',
    'stax': 'steraks',
    'drag': 'dryad',
    'riad': 'dryad',
    'scbo scra': 'scoreboard scrapper',
    'cl': 'cloak',
    'mor': 'morello',
    'melo': 'morello',
    'mel': 'morello',
    'mallo': 'morello',
    'eon': 'econ',
    'ja': 'jax',
    'jacks': 'jax',
    'lucky pause': 'lucky paws',
    'aurelia': 'irelia',
    'aelia': 'irelia',
    'aia': 'irelia',
    'ael': 'irelia',
    'relia': 'irelia',
    'loki': 'lowkey',
    'rabit on': 'rabadon',
    'alloi': 'illaoi',
    'tiar': 'tear',
    'tier': 'tear',
    'nar': 'gnar',
    'greeting': 'greeding',
    'raon': 'rakan',
    'rockon': 'rakan',
    'kiyana': 'qiyana',
    'kiana': 'qiyana',
    'hiana': 'qiyana',
    'yori': 'yorick',
    'ginsoo': 'guinsoo',
    'ginsu': 'guinsoo',
    'kinsu': 'guinsoo',
    'umbrella': 'umbral',
    'umbrell': 'umbral',
    'dualist': 'duelist',
    'bel': 'belt',
    'declaw': 'dclaw',
    'innovating': 'innervating',
    'ribon': 'riven',
    'silas': 'sylas',
    'ash': 'ashe',
    'blove': 'glove',
    'trimo': 'teemo',
    'aloon': 'alune',
    'elun': 'alune',
    'shojun': 'shojin',
    'ari': 'ahri',
    'yuo': 'yasuo',
    'mal fight': 'malphite',
    'kindra': 'kindred',
    'faded': 'fated',
    'rex side': 'reksai',
    'baelee': 'melee',
    'ezy rod': 'zzrot',
    'aellos': 'aphelios',
    'kogal': 'kogmaw',
    'ailos': 'aphelios',
    'udir': 'udyr',
    'kisis': 'kaisas',
    'eth': 'eigth',
    'ciper': 'sniper',


}
